# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-29 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0011_auto_20190319_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takenrecord',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
