# Generated by Django 2.1.7 on 2019-03-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0011_auto_20190319_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='img',
            field=models.ImageField(default='E:\\Workspace\\PyCharm-workspace\\lostfound\\staticdefault_img.jpg', upload_to='img/object'),
        ),
    ]
