# Generated by Django 2.1.7 on 2019-03-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0012_auto_20190325_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='img',
            field=models.ImageField(default='default_img.jpg', upload_to='img/object'),
        ),
    ]
