# Generated by Django 2.1.7 on 2019-03-25 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0015_auto_20190325_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userobject',
            name='object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='model.Object'),
        ),
    ]
