# Generated by Django 2.1.7 on 2019-03-25 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0016_auto_20190325_2106'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userobject',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userobject',
            name='object',
        ),
        migrations.RemoveField(
            model_name='userobject',
            name='user',
        ),
        migrations.AddField(
            model_name='object',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='model.User'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserObject',
        ),
    ]
